version: '3.4'
services:
  ecommerce:
    container_name: ecommerce
    working_dir: /home/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - ecommerce
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./:/home/app
      - ./.env:/home/app/ecom/.env
  postgres:
    image: bitnami/postgresql:16.1.0
    volumes:
      - postgresql_data:/bitnami/postgresql
    env_file: .env
    networks:
      - ecommerce
    ports:
      - "5432:5432"

volumes:
  postgresql_data:

networks:
  ecommerce:
    driver: bridge