# Generated by Django 3.0.6 on 2024-04-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_fill_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/product.png', upload_to='product_images'),
        ),
    ]
